# Generated by Django 2.2.6 on 2019-10-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('Reference', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=200)),
                ('Prixunitaire', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('Code_Categorie', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=300)),
                ('Illustration', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('CodeDepot', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('AdresseDepot', models.CharField(max_length=200)),
                ('VilleDepot', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QteEnStock', models.CharField(max_length=200)),
                ('SeuilStock', models.CharField(max_length=200)),
                ('CodeeDepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Depot')),
                ('Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Code_Categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Categorie'),
        ),
    ]
