# Generated by Django 2.2.6 on 2019-10-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocker',
            unique_together={('CodeeDepot', 'Reference')},
        ),
    ]
