# Generated by Django 2.2.2 on 2019-10-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('Reference', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=25)),
                ('PrixUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('Designation',),
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('CodeCategorie', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('LibelleCategorie', models.CharField(max_length=35)),
                ('Illustration', models.FileField(blank=True, upload_to='uploads/')),
            ],
            options={
                'ordering': ('LibelleCategorie',),
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('CodeDepot', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AdresseDepot', models.CharField(max_length=50)),
                ('VilleDepot', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('CodeDepot',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QteEnStock', models.IntegerField()),
                ('SeuilStock', models.IntegerField()),
                ('CodeDepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Depot')),
                ('Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Articles')),
            ],
            options={
                'unique_together': {('CodeDepot', 'Reference')},
            },
        ),
        migrations.AddField(
            model_name='depot',
            name='Articles',
            field=models.ManyToManyField(through='stock.Stock', to='stock.Articles'),
        ),
        migrations.AddField(
            model_name='articles',
            name='CodeCategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Categorie'),
        ),
    ]
